### PR TITLE
Fix/recent history

### LINKED ISSUE #86: Fix recent history on search screen
Fix recent history on search screen

### PR DESCRIPTION
**Pull request by haideraljawasim**
What have been done :
- add the functionality   search with query clicked 
- implement logic to display content when user didn't search before 
- add animation on state change like delete recent search 
- add the functionality to add recent viewed media   when user click movie or series

### CODE REVIEW

File: feature/search/presentation/src/main/java/com/sanaa/presentation/screen/state/SearchScreenUiState.kt [hunk 1]
```diff
@@ -1,13 +1,13 @@
...
 import usecase.search.MediaFilters
 
 
 data class SearchScreenUiState(
     val searchQuery: String = "",
     val selectedTabIndex: Int = 0,
-    val recentViewedImageUrls: List<String> = emptyList(),
-    val recentSearchQueries: List<String> = emptyList(),
+    val resentViewedImageList: List<RecentViewedUiModel> = emptyList(),
+    val resentSearchTitleList: List<RecentSearchUiModel> = emptyList(),
```
Comment (ZainabAlnajjar) [inline feature/search/presentation/src/main/java/com/sanaa/presentation/screen/state/SearchScreenUiState.kt]: return the old naming

File: feature/search/presentation/src/main/java/com/sanaa/presentation/screen/SearchScreenInteractionsListener.kt [hunk 2]
```diff
@@ -1,14 +1,17 @@
 package com.sanaa.presentation.screen
 
+import com.sanaa.presentation.state.RecentViewedUiModel
 import usecase.search.MediaFilters
 
 interface SearchScreenInteractionsListener {
     fun onClearRecentViewClicked()
     fun onClearRecentSearchClicked()
-    fun onCancelRecentSearchItemClicked(searchText: String)
+    fun onCancelRecentSearchItemClicked(id: Int)
```
Comment (ZainabAlnajjar) [inline feature/search/presentation/src/main/java/com/sanaa/presentation/screen/SearchScreenInteractionsListener.kt]: we are deleting the item with this interaction, please change to `onDeleteRecentSearchItemClicked`

**Review by ZainabAlnajjar — APPROVED** [review]

**Review by Ahmed7osny1 — APPROVED** [review]
