### PR TITLE
Fix filter bottom sheet Ui and logic

### LINKED ISSUE #317: fix/search filter by genre
filter by genres is not correctly implemented, it shows more media when selecting more genres to filter with (the opposite of filtering)

### LINKED ISSUE #351: issue:search: Minimum start year
Minimum start year is 1980 (there is a lot of movies and tvshow older than that)

make the filter have minimum and maximum of (1850 - current year)

### LINKED ISSUE #360: In filter bottom sheet the padding between the genres and the slider is not correct, it's different from the one in Figma
https://thechance-workspace.slack.com/archives/C08R9ULD7NG/p1753718673181689?thread_ts=1753642800.489039&cid=C08R9ULD7NG

### LINKED ISSUE #375: fix/squre ripple when it should be rounded cornel ripple or without it in filter bottom sheet
https://github.com/user-attachments/assets/fe51f191-fdc8-40e0-864b-19a363859141

### LINKED ISSUE #377: Huge delay when opening filter bottom sheet

### LINKED ISSUE #378: The chips in the filter bottom sheet cannot have an animation.

### LINKED ISSUE #379: Genre filters for TV shows are incorrectly affecting movies. Filters for TV shows and movies should work independently.

### PR DESCRIPTION
**Pull request by hagarabobakr**
Fixed genre filters affecting both movies and TV shows — now they work independently.

Disabled chip animation in the filter bottom sheet.

Improved performance by reducing delay when opening the filter sheet.

Updated ripple effect on chips to be rounded.

Adjusted padding between genres and slider to match Figma.

Fixed incorrect genre filtering logic when selecting multiple genres — now it returns only media that matches all selected genres.
make the filter have minimum and maximum of (1850 - current year)

### CODE REVIEW

**Review by shahad-97 — DISMISSED** [review]

File: feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt [hunk 1]
```diff
@@ -36,190 +35,204 @@ class FilterViewModelTest {
...
+//    fun `onApplyClicked() should return media filters with selected genres`() = runTest {
+//        val genre = genres[0]
+//        val rate = 1f
+//
+//        filterViewModel.onRatingChanged(rate.toInt())
+//        filterViewModel.onGenreSelected(genre)
+//        filterViewModel.onApplyClicked()
+//
+//        filterViewModel.filterResult.test {
+//            val item = awaitItem()
```
Comment (AhmadKharfan) [inline feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt]: why this comments??

Comment (hagarabobakr) [reply feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt]: I forgot them.

**Review by shahad-97 — APPROVED** [review]

**Review by AhmadKharfan — APPROVED** [review]
Good Job
