### PR TITLE
fix tv topRated endpoint & movie

### LINKED ISSUE #353: issue:home: top rated api
make sure that the app is using the right top rated api as reported

- Top rated tv shows are also not top rated tv shows 
- Top rated movies are not the top rated movies

### PR DESCRIPTION
**Pull request by ElhamFadel**

### CODE REVIEW

**Review by ZainabAlnajjar — CHANGES_REQUESTED** [review]
please check on my comments below, your approach is not working with genre filtration, and that is against the requirements

File: data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt [hunk 1]
```diff
@@ -62,7 +62,7 @@ interface MovieApiService {
         @Query("release_date.lte") maxDate: String? = null,
     ): MovieApiResponse<MovieDto>
 
-    @GET("discover/movie")
+    @GET("movie/top_rated")
```
Comment (ZainabAlnajjar) [inline data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt]: there is no `with_genres` parameter in the endpoint, I tested it myself, you can check this [link](https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1&api_key=ba21689db16b6c3bc58c8f5c53ebd129&without_genres=14) and try the results, you would notice the parameter is not working here

if you can return to the documentation, it says that this call is just a discovery call behind the scenes, just with extra parameters as you see, please refactor this part based on the documentation in this [link](https://developer.themoviedb.org/reference/movie-top-rated-list)

image

File: data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/tvShow/TvShowApiService.kt [hunk 2]
```diff
@@ -84,7 +84,7 @@ interface TvShowApiService {
         @Query("release_date.lte") maxDate: String? = null,
     ): MovieApiResponse<TvShowDto>
 
-    @GET("discover/tv")
+    @GET("tv/top_rated")
```
Comment (ZainabAlnajjar) [inline data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/tvShow/TvShowApiService.kt]: same thing here [link](https://developer.themoviedb.org/reference/tv-series-top-rated-list)

File: data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/tvShow/TvShowApiService.kt [hunk 3]
```diff
@@ -74,7 +74,7 @@ interface TvShowApiService {
         @Query("page") page: Int
     ): MovieApiResponse<TvShowDto>
 
-    @GET("discover/tv")
+    @GET("trending/tv/week")
     suspend fun fetchTrendingTvShows(
         @Query("page") page: Int,
         @Query("with_genres") withGenres: String? = null,
```
Comment (ZainabAlnajjar) [inline data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/tvShow/TvShowApiService.kt]: trending also doesn't have `with_genres` parameter, you can check this query [link](https://[api.themoviedb.org/3/trending/tv/week?language=en-US&page=1&api_key=ba21689db16b6c3bc58c8f5c53ebd129&with_genres=18](https://api.themoviedb.org/3/trending/tv/week?language=en-US&page=1&api_key=ba21689db16b6c3bc58c8f5c53ebd129&with_genres=18)), so please return the previous discovery and maybe search for a better way to handle its parameters, although I believe it was ok as it is, you can check this link to know more about the difference [link](https://developer.themoviedb.org/docs/popularity-and-trending)

File: data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt [hunk 4]
```diff
@@ -52,7 +52,7 @@ interface MovieApiService {
         @Query("page") page: Int
     ): MovieApiResponse<MovieDto>
 
-    @GET("discover/movie")
+    @GET("trending/movie/week")
```
Comment (ZainabAlnajjar) [inline data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt]: same here

File: data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt (hunk 1 above)
Comment (ElhamFadel) [reply data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt]: we don't need geners here

Comment (ElhamFadel) [reply data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt]: I got you,it will effect on other side

Comment (ZainabAlnajjar) [reply data/remote_data_source/vod/src/main/java/com/sanaa/vod/media/movie/MovieApiService.kt]: We need the genres, please just add the needed parametees to match the query in documentation

**Review by ZainabAlnajjar — APPROVED** [review]

**Review by hagarabobakr — APPROVED** [review]

**Review by shahad-97 — APPROVED** [review]

**Comment by shahad-97** [comment]
Well done
