### PR TITLE
solve actor search bug

### LINKED ISSUE #97: actors search bug
searching with actors sometimes doesn't show result or show only one actor

### PR DESCRIPTION
**Pull request by ElhamFadel**

### CODE REVIEW

File: data/local_data_source/search/src/main/java/com/sanaa/search/search_result/dao/ActorDao.kt [hunk 1]
```diff
@@ -11,6 +11,6 @@ interface ActorDao {
     @Insert(onConflict = OnConflictStrategy.REPLACE)
     suspend fun insertActor(actor: ActorsLocalDto)
 
-    @Query("SELECT * FROM actor WHERE LOWER(name) LIKE '%' || LOWER(:query) || '%' LIMIT 1")
-    suspend fun getActorByQuery(query: String): ActorsLocalDto?
+    @Query("SELECT * FROM actor WHERE LOWER(name) LIKE '%' || LOWER(:query) || '%'")
+    suspend fun getActorsByQuery(query: String): List<ActorsLocalDto>
```
Comment (Ahmed7osny1) [inline data/local_data_source/search/src/main/java/com/sanaa/search/search_result/dao/ActorDao.kt:15]: use flow to reactive and lifecycle-aware

File: data/local_data_source/search/src/main/java/com/sanaa/search/search_result/LocalCachedSearchDataSourceImpl.kt [hunk 2]
```diff
@@ -82,11 +82,11 @@ class LocalCachedSearchDataSourceImpl(
 
         if (cachedResults.isNotEmpty()) {
             return cachedResults.mapNotNull { result ->
```
Comment (Ahmed7osny1) [inline data/local_data_source/search/src/main/java/com/sanaa/search/search_result/LocalCachedSearchDataSourceImpl.kt:84]: Use flatmap when expecting the inner function to return a list or sequence,
mapNotNull is used when a single value will be returned or none from the inner function

**Review by Ahmed7osny1 — APPROVED** [review]

File: data/local_data_source/search/src/main/java/com/sanaa/search/search_result/LocalCachedSearchDataSourceImpl.kt (hunk 2 above)
Comment (ElhamFadel) [reply data/local_data_source/search/src/main/java/com/sanaa/search/search_result/LocalCachedSearchDataSourceImpl.kt:84]: thanks Ahmed :>

**Review by EL-MANCY — APPROVED** [review]

**Review by ZainabAlnajjar — APPROVED** [review]
Good job Elham

**Review by hagarabobakr — APPROVED** [review]
