### PR TITLE
Fix/unit test

### LINKED ISSUE #84: fix unit test
Fix some unit test that failed

### PR DESCRIPTION
**Pull request by AimanYosofiUlt**
Prepare unit test for the part that has not been tested before to increase the coverage from 9% to 95%

### CODE REVIEW

File: feature/search/presentation/src/main/java/com/sanaa/presentation/filter_bottomsheet/state/FilterUiState.kt [hunk 1]
```diff
@@ -4,9 +4,9 @@ import entity.Genre
 
 data class FilterUiState(
     val yearRange: ClosedFloatingPointRange<Float> = 1980f..2025f,
-    val allGenres: List<Genre> = emptyList(),
+    val allGenres: List<Genre> = Genre.entries,
     val selectedGenres: Set<Genre> = emptySet(),
     val imdbRating: Int = 0,
-    val isLoading: Boolean = true,
+    val isLoading: Boolean = false,
```
Comment (Radwa85) [inline feature/search/presentation/src/main/java/com/sanaa/presentation/filter_bottomsheet/state/FilterUiState.kt:10]: i think We should keep it true by default and set it to false after loading finishes. Let me know if there's a specific reason for the change

File: feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+            val expected = FilterUiState(
+                imdbRating = rate,
+                isDefaultState = false
+            )
+            Truth.assertThat(item).isEqualTo(expected)
+        }
+    }
+
+    @Test
+    fun `onClearFilters()`() = runTest {
```
Comment (Radwa85) [inline feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt]: using function name as name of test not enough , u can add more description

File: feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+        // Then
+        filterViewModel.uiState.test {
+            val item = awaitItem()
+            val expected = FilterUiState(yearRange = range, isDefaultState = false)
+            Truth.assertThat(item).isEqualTo(expected)
+        }
+    }
+
+    @Test
+    fun `onGenreSelected() should change genre`() = runTest {
```
Comment (Radwa85) [inline feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt]: add when statement too

File: feature/search/presentation/src/main/java/com/sanaa/presentation/filter_bottomsheet/state/FilterUiState.kt (hunk 1 above)
Comment (AimanYosofiUlt) [reply feature/search/presentation/src/main/java/com/sanaa/presentation/filter_bottomsheet/state/FilterUiState.kt:10]: There is no loading data happening in the initial

File: feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+        // When
+        filterViewModel.onYearRangeChanged(range)
+
+        // Then
+        filterViewModel.uiState.test {
+            val item = awaitItem()
+            val expected = FilterUiState(yearRange = range, isDefaultState = false)
+            Truth.assertThat(item).isEqualTo(expected)
+        }
+    }
```
Comment (ZainabAlnajjar) [inline feature/search/presentation/src/test/java/com/sanaa/presentation/filter_bottomsheet/FilterViewModelTest.kt]: I think it would be clearer to say it would update the state instead of changing the range, like this:
`onYearRangeChanged() should update filter state when called`, same for other tests

also, you cold import the `assertThat `instead of calling it from `Truth.assertThat` -> `assertThat`

**Review by ZainabAlnajjar — APPROVED** [review]

**Review by Radwa85 — APPROVED** [review]

**Review by mostafa-n3ma — APPROVED** [review]

**Review by shahad-97 — APPROVED** [review]
