### PR TITLE
Fix/UI issues

### LINKED ISSUE #490: Fix some issues in UI
Fix system bar padding in home screen 
Fix recreate the activity on selecting the same lang

### PR DESCRIPTION
**Pull request by haideraljawasim**
# What have been done :
- Fix padding in home screen 
- only update stored value for user preferences if it different from what was before

### CODE REVIEW

**Review by raouf-kamel — APPROVED** [review]
good job

File: feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/myAccount/MyAccountScreenViewModel.kt [hunk 1]
```diff
@@ -93,12 +100,16 @@ class MyAccountScreenViewModel @Inject constructor(
...
+        val previousContentRestriction =
+            runBlocking { mangeUserPreference.getContentRestriction().first() }
+        if (previousContentRestriction.name != state.value.selectedContentRestriction?.name)
+            tryToExecute(
+                callee = { saveContentRestriction() },
+                onSuccess = {
+                    updateState { it.copy(showContentRestrictionBottomSheet = false) }
+                }
+            )
+        else updateState { it.copy(showContentRestrictionBottomSheet = false) }
```
Comment (mostafa-n3ma) [inline feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/myAccount/MyAccountScreenViewModel.kt:112]: Nice 👌

File: feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/myAccount/MyAccountScreenViewModel.kt [hunk 2]
```diff
@@ -80,10 +84,13 @@ class MyAccountScreenViewModel @Inject constructor(
...
 
     override fun onSaveThemeClick() {
-        tryToExecute(
-            callee = { saveTheme() },
-            onSuccess = ::onSaveThemeSuccess
-        )
+        val previousTheme = runBlocking { mangeUserPreference.getTheme().first() }
+        if (previousTheme.name != state.value.selectedTheme?.name)
+            tryToExecute(
+                callee = { saveTheme() },
```
Comment (mostafa-n3ma) [inline feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/myAccount/MyAccountScreenViewModel.kt:90]: Everything looks great but there's no error handling !

**Review by mostafa-n3ma — APPROVED** [review]
