### PR TITLE
Fix/284 fix filter bottom sheet

### LINKED ISSUE #284: Fix filter bottom sheet

### PR DESCRIPTION
**Pull request by hagarabobakr**
fix filter bottom sheet behavior

### CODE REVIEW

File: feature/search/presentation/src/main/java/com/sanaa/presentation/filter_bottomsheet/FilterBottomSheet.kt [hunk 1]
```diff
@@ -70,31 +76,21 @@ fun FilterBottomSheet(
...
     Column(
         modifier = Modifier
             .background(color = Theme.colors.surface)
             .fillMaxWidth()
-            .padding(
-                start = 16.dp,
-                end = 16.dp,
-                bottom = 24.dp
-            ),
+            .padding(16.dp),
```
Comment (raouf-kamel) [inline feature/search/presentation/src/main/java/com/sanaa/presentation/filter_bottomsheet/FilterBottomSheet.kt:92]: Check the padding top

**Review by raouf-kamel — APPROVED** [review]
keep it up, hagar

**Review by shahad-97 — APPROVED** [review]
