### PR TITLE
fix/observe-preferences-change

### LINKED ISSUE #633: Genres localization not updated immediately
When the application language is switched to Arabic, the genres do not get translated instantly. The translation only appears after closing and reopening the application.

### PR DESCRIPTION
**Pull request by mostafa-n3ma**

### CODE REVIEW

File: feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt [hunk 1]
```diff
@@ -47,14 +48,35 @@ class HomeScreenViewModel @Inject constructor(
...
+            block = {
+                mangeUserPreference.getLanguage().distinctUntilChanged()
+            },
+            onCollect = {
+                fetchPopularMediaData()
+                fetchTopRatedMediaData()
+                fetchMovieGenres()
+                fetchUpcomingMovies()
+                if (state.value.userIsLoggedIn) {
+                    fetchWatchedMediaData()
```
Comment (haideraljawasim) [inline feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt]: You already check on success of getting user logged in, and getting watched history  no need here to fetch it again

File: feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt [hunk 2]
```diff
@@ -63,7 +85,10 @@ class HomeScreenViewModel @Inject constructor(
     }
 
     private fun onCollectLoggedFlag(isLogged: Boolean) {
-        updateState { copy(userIsLoggedIn = isLogged, showLoginBottomSheet = false) }
+        if (isLogged != state.value.userIsLoggedIn) {
+            fetchWatchedMediaData()
```
Comment (haideraljawasim) [inline feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt:74]: What I mean is you should just call fetchWatchedMediaData() if the user is logged in there’s no point in duplicating this check with the userIsLoggedIn state

**Review by ZainabAlnajjar — APPROVED** [review]

**Review by shahad-97 — APPROVED** [review]
