### PR TITLE
Fix/date parser

### LINKED ISSUE #583: fix: date parser
the app crash when the api return the date as empty string, also remove the default 1900-1-1 date when api return null date

### PR DESCRIPTION
**Pull request by ZainabAlnajjar**
# What have been done
- fix crash of returning null or empty date from api 
- all entities has non-nullable date now
- add function to parse the date safely or return default value of LocalDate(1, 1, 1) if date is invalid
- handle the above changes in ui

### CODE REVIEW

File: data/repositories/vod/src/main/java/com/sanaa/vod/repository/mapper/media/episodeMapper.kt [hunk 1]
```diff
@@ -13,7 +13,7 @@ fun EpisodeDto.toEntity(): Episode {
         number = episodeNumber,
         imdbRating = voteAverage,
         durationMinutes = runtime,
-        releaseDate = airDate?.let { LocalDate.parse(it) } ?: LocalDate.parse("1970-01-01"),
+        releaseDate = getLocalDateOrDefault(airDate),
```
Comment (mostafa-n3ma) [inline data/repositories/vod/src/main/java/com/sanaa/vod/repository/mapper/media/episodeMapper.kt:16]: try : safeParseLocalDate(airDate)

File: data/repositories/vod/src/main/java/com/sanaa/vod/util/DateTimeUtils.kt [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+import kotlinx.datetime.LocalDate
+
+object DateTimeUtils {
+    fun getCurrentTimeStamp(): Long {
+        return System.currentTimeMillis()
+    }
+
+    fun getLocalDateOrDefault(date: String?): LocalDate {
+        return try {
+            LocalDate.parse(date ?: "")
```
Comment (mostafa-n3ma) [inline data/repositories/vod/src/main/java/com/sanaa/vod/util/DateTimeUtils.kt:12]: the try catch feels like you are handling the failure exception  without validating first

**Review by AhmadKharfan — APPROVED** [review]

File: data/repositories/vod/src/main/java/com/sanaa/vod/util/DateTimeUtils.kt (hunk 2 above)
Comment (ZainabAlnajjar) [reply data/repositories/vod/src/main/java/com/sanaa/vod/util/DateTimeUtils.kt:12]: it will throw exception either ways, didn't want to make more unnecessary checks

**Review by AimanYosofiUlt — APPROVED** [review]
