### PR TITLE
Fix/search filters not working properly

### LINKED ISSUE #174: Fix search filters not working properly
- Filters not working properly (missing a lot of media in filter result)
- When applying filters, search won't refresh until you switch tab then return

### PR DESCRIPTION
**Pull request by ZainabAlnajjar**
- [x] Filters not working properly (missing a lot of media in filter result)
- [x] When applying filters, search won't refresh until you switch tab then return

### CODE REVIEW

File: data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt [hunk 1]
```diff
@@ -178,9 +165,9 @@ class SearchRepositoryImpl(
     private suspend fun <T> searchOrThrow(query: String, callee: suspend () -> T): T {
```
Comment (hagarabobakr) [inline data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt]: I think if the function name is 'safeCall' it will be more readable.

File: data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt [hunk 2]
```diff
@@ -35,14 +34,9 @@ class SearchRepositoryImpl(
...
                 }
-                return actors.map { it.toSearchOutput() }
+                actors.map { it.toSearchOutput() }
             }
-        } catch (_: UnknownHostException) {
-            throw NoNetworkException()
-        } catch (_: Exception) {
-            throw RetrievingDataFailureException("Failed to retrieve actors for query: $query")
         }
-    }
```
Comment (hagarabobakr) [inline data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt]: Suggestion: Move the filtering logic from searchMovies and searchTvShows to shared private functions within the file.

Comment (ZainabAlnajjar) [reply data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt]: @AimanYosofiUlt did that in his branch, my branch is to fix the logic only, we will combine them

File: feature/search/presentation/src/main/java/com/sanaa/presentation/screen/componants/SearchHistoryContent.kt [hunk 3]
```diff
@@ -114,9 +114,7 @@ fun SearchHistoryContent(
                                         }
                                     },
                                     topLeftContent = {
-                                        SaveIconChip(
-                                            onClick = interactionsListener::onSaveIconClicked
-                                        )
+                                        SaveIconChip(onClick = {})
```
Comment (hagarabobakr) [inline feature/search/presentation/src/main/java/com/sanaa/presentation/screen/componants/SearchHistoryContent.kt]: Why did we delete 
onClick = interactionsListener::onSaveIconClicked
 from here?

**Review by hagarabobakr — DISMISSED** [review]
Good job 👏

File: data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt [hunk 4]
```diff
@@ -52,24 +46,22 @@ class SearchRepositoryImpl(
...
-                }
+                filteredMedia =
+                    filteredMedia.filter {
+                        (it.imdbRating ?: 0f) >= filters.imdbRating
+                                && it.releaseYear != null
+                                && it.releaseYear >= filters.startYear
+                                && it.releaseYear <= filters.endYear
+                    }
 
                 filteredMedia.map { it.toSearchOutput() }
```
Comment (hagarabobakr) [inline data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt]: This result is not returned from the function  you need to return it using return.

File: data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt [hunk 5]
```diff
@@ -88,20 +80,18 @@ class SearchRepositoryImpl(
...
+                    movies.filter { series ->
+                        val genreIds = series.genreIds?.toSet() ?: emptySet()
+                        filterGenreIds.all { it in genreIds }
+                    }
 
-                filters.imdbRating?.let { rating ->
-                    filteredMedia = filteredMedia.filter { (it.voteAverage ?: 0f) >= rating }
+                filteredMedia = filteredMedia.filter {
+                    (it.voteAverage ?: 0f) >= filters.imdbRating
+                            && it.releaseDate != null &&
```
Comment (hagarabobakr) [inline data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt]: LocalDate.parse is being called twice on the same value within the same condition. It's better to parse it once and store the result in a variable like:
val year = it.releaseDate?.let { date -> LocalDate.parse(date).year }
This improves performance slightly and enhances readability ^^

**Review by shahad-97 — DISMISSED** [review]

File: data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt (hunk 4 above)
Comment (ZainabAlnajjar) [reply data/repositories/search/src/main/java/com/sanaa/search/repository/SearchRepositoryImpl.kt]: it is returning the last line in each condition

File: feature/search/presentation/src/main/java/com/sanaa/presentation/screen/componants/SearchHistoryContent.kt (hunk 3 above)
Comment (ZainabAlnajjar) [reply feature/search/presentation/src/main/java/com/sanaa/presentation/screen/componants/SearchHistoryContent.kt]: it is failing the tests without any useful usage, we can implement it later

**Review by shahad-97 — APPROVED** [review]

**Review by AimanYosofiUlt — APPROVED** [review]
